# permissions for end users to edit beholders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: beholder-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podview
    app.kubernetes.io/part-of: podview
    app.kubernetes.io/managed-by: kustomize
  name: beholder-editor-role
rules:
- apiGroups:
  - monster.podview.killbot99.io
  resources:
  - beholders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monster.podview.killbot99.io
  resources:
  - beholders/status
  verbs:
  - get
